# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e07a8574210269e36a7a9047d77966dab1f16a1fb51dfd8c9a4ec826d96197c5b31482600eeaa84836fffc390e923b903e0ca5f8f31a74ec5e5b6ca7583cf93

test:
  secret_key_base: 06021846c241d31c696e358197693938dcdcc54716cbf8e2b87e9d5b37150307fb3ac75c52dd7c4381cc9720ee021f30d7270b3d28b7533096122312f3486d1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
